#
# VexelCore Proxy Config File
#
# Please visit the wiki for detailed information :)
#

prefix = "&aVCP &8>>"

[vcp-main]
enabled = true

[customCommand]
enabled = true
data = [
    { type = "playerProxyExecute", newCommand = "hub", execute = "server hub", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "survival", execute = "server survival", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "nds", execute = "server natural-disasters", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "nds2", execute = "server natural-disasters2", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "creative", execute = "server creative", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "tnt", execute = "server tntrunv2", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "td", execute = "server towerdefense", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "snapshot", execute = "server snapshot", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "events", execute = "server events", passArgs = "no" },
    { type = "playerProxyExecute", newCommand = "walls", execute = "server walls", passArgs = "no" },
    { type = "playerServerExecute", newCommand = "helpplz", execute = "help", passArgs = "yes" },
    # Component Actions: OPEN_URL, RUN_COMMAND, SUGGEST_COMMAND, COPY_TO_CLIPBOARD
    # All actions must include content, action, and actionValue.
    { type = "message", newCommand = "secretmessage", components = [ { content = "&3Click me...", hover = "&7Click to copy a secret message!", action = "COPY_TO_CLIPBOARD", actionValue = "You're a nerd!" } ] },
    { type = "message", newCommand = "discord", components = [ { content = "&7Click to join our &3Discord", hover = "&7Click me", action = "OPEN_URL", actionValue = "https://discord.gg/V4ukMbe" } ] },
    { type = "message", newCommand = "website", components = [ { content = "&7Click to view our &3website", hover = "&7Click me", action = "OPEN_URL", actionValue = "https://southhollow.net/" } ] },
    { type = "message", newCommand = "store", components = [ { content = "&7Click to view our &3store", hover = "&7Click me", action = "OPEN_URL", actionValue = "https://southhollow.net/" } ] },
    { type = "message", newCommand = "help", components = [ { content = "&7Please join our &3/discord &7for support.", hover = "&7Click to run &3/discord", action = "RUN_COMMAND", actionValue = "/discord" } ] },
    { type = "message", newCommand = "nerd", components = [ { content = "&7You're a nerd", action = "RUN_COMMAND", actionValue = "I'm a nerd!" } ] },
]

[glist]
enabled = true

[jump]
enabled = true

[broadcast]
enabled = true
prefix = "&7[&aBroadcast&7]" # The prefix that appears in the title and chat
hoverInfo = "&7Sender: &3%sender%" # Text shown in when hovering over the broadcast chat prefix
alwaysSendChatBroadcast = true # If broadcast is a title or actionbar, additionally send the broadcast in chat.
consoleName = "CONSOLE" # The %sender% variable name if the broadcast is sent through the console.

[permissions]
staff = "vcp.staff" # for /vcp
glist = "vcp.glist" # for /glist
jump = "vcp.jump" # for /jump
broadcast = "vcp.broadcast" # for /broadcast

[language]
serverName = "&aSouthHollow Network"
bar = "&r&8&m                 "
helpL1 = "&3/vcp &7help &8- &7Displays these help chat messages"
helpL2 = "&3/vcp &7version &8- &7Displays version information"
helpL3 = "&3/vcp &7reload &8- &7Reloads plugin config."
helpL4 = "&3/vcp &7features &8- &7Displays the enabled plugin features"
helpL5 = "&3/vcp &7cc &8- &7Displays help for custom commands"
helpL6 = "&3Important Note: &7This plugin is modular. Please check the config.toml file to see which features you want to enable and or customize."
helpC1 = "&7CC help coming soon... Use &3/vcp cc list &7to preview currently loaded custom commands."
reloadedConfig = "&7The configuration has been reloaded."
noPermission = "&c(!) &7You do not have the required permission for this command!"
invalidUsage = "&7Usage: &3"
canOnlyBeExecutedByAPlayer = "&c(!) &7This can only be executed by a player!"
creatingConnectionRequest = "&7Creating connection request to &3%server%&7..."
alreadyConnected = "&cYou're already connected to that server!"
broadcastSentSuccessfully = "&3The broadcast sent successfully!"